const PRIMARY_BLUE = "#5FB2CA";
const OPAQUE_BLUE = "rgba(95, 178, 202, .7)";
const SECONDARY_BLUE = "#162432";

const PRIMARY_PURPLE = "#646591";
const OPAQUE_PURPLE = "rgba(100, 101, 145, .9)";
const SECONDARY_PURPLE = "#9866c7";

const PRIMARY_WHITE = "#ffffff";
const SECONDARY_WHITE = "#F6F8FC";

const PRIMARY_BLACK = "#000000";
const PRIMARY_GRAY = "#D3D3D3";

export default {
  BG_PRIMARY: SECONDARY_BLUE,
  BG_SECONDARY: SECONDARY_WHITE,

  TEXT_PRIMARY: PRIMARY_WHITE,
  TEXT_SECONDARY: PRIMARY_GRAY,
  TEXT_TERTIARY: PRIMARY_BLACK,

  GRADIENT_COLORS: [OPAQUE_BLUE, OPAQUE_PURPLE],
  GRADIENT_START: { x: 0, y: 0 },
  GRADIENT_END: { x: 1, y: 1 },

  FONT_PRIMARY: "Roboto",
  FONT_SECONDARY: "notoserif",

  PRIMARY_BLUE,
  OPAQUE_BLUE,
  PRIMARY_PURPLE,
  OPAQUE_PURPLE,
  SECONDARY_BLUE,
  SECONDARY_PURPLE,
};
